name: clean1
version: 1.0.0
config-version: 2
profile: clean1
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  clean1:
    +materialized: view
